// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `i18n.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcI18N;

public abstract class Callback_I18NEndpoint_check
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<ResourceResponse>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        I18NEndpointPrxHelper.__check_completed(this, __result);
    }
}
