// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `i18n.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcI18N;

public final class CheckResourceVersionRequestHolder extends Ice.ObjectHolderBase<CheckResourceVersionRequest>
{
    public
    CheckResourceVersionRequestHolder()
    {
    }

    public
    CheckResourceVersionRequestHolder(CheckResourceVersionRequest value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof CheckResourceVersionRequest)
        {
            value = (CheckResourceVersionRequest)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return CheckResourceVersionRequest.ice_staticId();
    }
}
