// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `i18n.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcI18N;

public interface I18NEndpointPrx extends Ice.ObjectPrx
{
    public ResourceResponse getLatest(String traceId, String lan);

    public ResourceResponse getLatest(String traceId, String lan, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatest(String traceId, String lan);

    public Ice.AsyncResult begin_getLatest(String traceId, String lan, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getLatest(String traceId, String lan, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatest(String traceId, String lan, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getLatest(String traceId, String lan, Callback_I18NEndpoint_getLatest __cb);

    public Ice.AsyncResult begin_getLatest(String traceId, String lan, java.util.Map<String, String> __ctx, Callback_I18NEndpoint_getLatest __cb);

    public Ice.AsyncResult begin_getLatest(String traceId,
                                           String lan,
                                           IceInternal.Functional_GenericCallback1<ResourceResponse> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getLatest(String traceId,
                                           String lan,
                                           IceInternal.Functional_GenericCallback1<ResourceResponse> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getLatest(String traceId,
                                           String lan,
                                           java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<ResourceResponse> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getLatest(String traceId,
                                           String lan,
                                           java.util.Map<String, String> __ctx,
                                           IceInternal.Functional_GenericCallback1<ResourceResponse> __responseCb,
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                           IceInternal.Functional_BoolCallback __sentCb);

    public ResourceResponse end_getLatest(Ice.AsyncResult __result);

    public ResourceResponse check(String traceId, CheckResourceVersionRequest request);

    public ResourceResponse check(String traceId, CheckResourceVersionRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_check(String traceId, CheckResourceVersionRequest request);

    public Ice.AsyncResult begin_check(String traceId, CheckResourceVersionRequest request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_check(String traceId, CheckResourceVersionRequest request, Ice.Callback __cb);

    public Ice.AsyncResult begin_check(String traceId, CheckResourceVersionRequest request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_check(String traceId, CheckResourceVersionRequest request, Callback_I18NEndpoint_check __cb);

    public Ice.AsyncResult begin_check(String traceId, CheckResourceVersionRequest request, java.util.Map<String, String> __ctx, Callback_I18NEndpoint_check __cb);

    public Ice.AsyncResult begin_check(String traceId,
                                       CheckResourceVersionRequest request,
                                       IceInternal.Functional_GenericCallback1<ResourceResponse> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_check(String traceId,
                                       CheckResourceVersionRequest request,
                                       IceInternal.Functional_GenericCallback1<ResourceResponse> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_check(String traceId,
                                       CheckResourceVersionRequest request,
                                       java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_GenericCallback1<ResourceResponse> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_check(String traceId,
                                       CheckResourceVersionRequest request,
                                       java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_GenericCallback1<ResourceResponse> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                       IceInternal.Functional_BoolCallback __sentCb);

    public ResourceResponse end_check(Ice.AsyncResult __result);
}
