// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `i18n.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcI18N;

public final class I18NEndpointHolder extends Ice.ObjectHolderBase<I18NEndpoint>
{
    public
    I18NEndpointHolder()
    {
    }

    public
    I18NEndpointHolder(I18NEndpoint value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof I18NEndpoint)
        {
            value = (I18NEndpoint)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _I18NEndpointDisp.ice_staticId();
    }
}
