// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `i18n.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcI18N;

public interface I18NEndpoint extends Ice.Object,
                                      _I18NEndpointOperations, _I18NEndpointOperationsNC
{
    public static final String ice_staticId = "::RpcI18N::I18NEndpoint";

    public static final long serialVersionUID = 3604927635904996639L;
}
