// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `i18n.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package RpcI18N;

public class ResourceResponse extends I18NBaseResponse
{
    public ResourceResponse()
    {
        super();
    }

    public ResourceResponse(String code, boolean isLatest, int latestVersion, Resource[] resourceList)
    {
        super(code);
        this.isLatest = isLatest;
        this.latestVersion = latestVersion;
        this.resourceList = resourceList;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new ResourceResponse();
        }

        public void destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::RpcI18N::I18NBaseResponse",
        "::RpcI18N::ResourceResponse"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[2];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[2];
    }

    public static String ice_staticId()
    {
        return __ids[2];
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, false);
        __os.writeBool(isLatest);
        __os.writeInt(latestVersion);
        ResourceSeqHelper.write(__os, resourceList);
        __os.endWriteSlice();
        super.__writeImpl(__os);
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        isLatest = __is.readBool();
        latestVersion = __is.readInt();
        resourceList = ResourceSeqHelper.read(__is);
        __is.endReadSlice();
        super.__readImpl(__is);
    }

    public boolean isLatest;

    public int latestVersion;

    public Resource[] resourceList;

    public ResourceResponse
    clone()
    {
        return (ResourceResponse)super.clone();
    }

    public static final long serialVersionUID = 7479305084181882031L;
}
