/**
 * Generated by Scrooge
 *   version: 4.5.0
 *   rev: 014664de600267b36809bbc85225e26aec286216
 *   built at: 20160203-205352
 */
package com.jxjxgo.i18n.rpc.domain

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object PullResourceRequest extends ThriftStructCodec3[PullResourceRequest] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("PullResourceRequest")
  val VersionField = new TField("version", TType.I32, 1)
  val VersionFieldManifest = implicitly[Manifest[Int]]
  val LanField = new TField("lan", TType.STRING, 2)
  val LanFieldManifest = implicitly[Manifest[String]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      VersionField,
      false,
      false,
      VersionFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      LanField,
      false,
      false,
      LanFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: PullResourceRequest): Unit = {
  }

  def withoutPassthroughFields(original: PullResourceRequest): PullResourceRequest =
    new Immutable(
      version =
        {
          val field = original.version
          field
        },
      lan =
        {
          val field = original.lan
          field
        }
    )

  override def encode(_item: PullResourceRequest, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): PullResourceRequest = {

    var version: Int = 0
    var lanOffset: Int = -1

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
    
                version = readVersionValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'version' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                lanOffset = _iprot.offsetSkipString
    
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'lan' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      version,
      lanOffset,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): PullResourceRequest =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): PullResourceRequest = {
    var version: Int = 0
    var lan: String = ""
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 =>
                version = readVersionValue(_iprot)
              case _actualType =>
                val _expectedType = TType.I32
                throw new TProtocolException(
                  "Received wrong type for field 'version' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRING =>
                lan = readLanValue(_iprot)
              case _actualType =>
                val _expectedType = TType.STRING
                throw new TProtocolException(
                  "Received wrong type for field 'lan' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      version,
      lan,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    version: Int = 0,
    lan: String = ""
  ): PullResourceRequest =
    new Immutable(
      version,
      lan
    )

  def unapply(_item: PullResourceRequest): _root_.scala.Option[scala.Product2[Int, String]] = _root_.scala.Some(_item)


  @inline private def readVersionValue(_iprot: TProtocol): Int = {
    _iprot.readI32()
  }

  @inline private def writeVersionField(version_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(VersionField)
    writeVersionValue(version_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeVersionValue(version_item: Int, _oprot: TProtocol): Unit = {
    _oprot.writeI32(version_item)
  }

  @inline private def readLanValue(_iprot: TProtocol): String = {
    _iprot.readString()
  }

  @inline private def writeLanField(lan_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(LanField)
    writeLanValue(lan_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeLanValue(lan_item: String, _oprot: TProtocol): Unit = {
    _oprot.writeString(lan_item)
  }


  object Immutable extends ThriftStructCodec3[PullResourceRequest] {
    override def encode(_item: PullResourceRequest, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): PullResourceRequest = PullResourceRequest.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[PullResourceRequest] = PullResourceRequest.metaData
  }

  /**
   * The default read-only implementation of PullResourceRequest.  You typically should not need to
   * directly reference this class; instead, use the PullResourceRequest.apply method to construct
   * new instances.
   */
  class Immutable(
      val version: Int,
      val lan: String,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends PullResourceRequest {
    def this(
      version: Int = 0,
      lan: String = ""
    ) = this(
      version,
      lan,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val version: Int,
      lanOffset: Int,
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends PullResourceRequest {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }

    lazy val lan: String =
      if (lanOffset == -1)
        ""
      else {
        _proto.decodeString(_buf, lanOffset)
      }

    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the PullResourceRequest trait with additional state or
   * behavior and implement the read-only methods from PullResourceRequest using an underlying
   * instance.
   */
  trait Proxy extends PullResourceRequest {
    protected def _underlying_PullResourceRequest: PullResourceRequest
    override def version: Int = _underlying_PullResourceRequest.version
    override def lan: String = _underlying_PullResourceRequest.lan
    override def _passthroughFields = _underlying_PullResourceRequest._passthroughFields
  }
}

trait PullResourceRequest
  extends ThriftStruct
  with scala.Product2[Int, String]
  with java.io.Serializable
{
  import PullResourceRequest._

  def version: Int
  def lan: String

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = version
  def _2 = lan


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (true) {
                writeVersionValue(version, _oprot)
                _root_.scala.Some(PullResourceRequest.VersionField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (lan ne null) {
                writeLanValue(lan, _oprot)
                _root_.scala.Some(PullResourceRequest.LanField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): PullResourceRequest = {
    var version: Int = this.version
    var lan: String = this.lan
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        version = readVersionValue(_blob.read)
      case 2 =>
        lan = readLanValue(_blob.read)
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      version,
      lan,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): PullResourceRequest = {
    var version: Int = this.version
    var lan: String = this.lan

    _fieldId match {
      case 1 =>
        version = 0
      case 2 =>
        lan = ""
      case _ =>
    }
    new Immutable(
      version,
      lan,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetVersion: PullResourceRequest = unsetField(1)

  def unsetLan: PullResourceRequest = unsetField(2)


  override def write(_oprot: TProtocol): Unit = {
    PullResourceRequest.validate(this)
    _oprot.writeStructBegin(Struct)
    writeVersionField(version, _oprot)
    if (lan ne null) writeLanField(lan, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    version: Int = this.version,
    lan: String = this.lan,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): PullResourceRequest =
    new Immutable(
      version,
      lan,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[PullResourceRequest]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[PullResourceRequest]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 2

  override def productElement(n: Int): Any = n match {
    case 0 => this.version
    case 1 => this.lan
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "PullResourceRequest"
}